name: Install UV Package Manager

description: Action to install UV and dependencies to run jobs.

runs:
  using: 'composite'
  steps:
    - name: Set up Python environment
      run: |
        echo "Setting up Python environment"
        uv python install 3.10
        uv python pin 3.10
      shell: bash
    