data_collection:
  env_vars:
    account_name : "rg_data_sci"
    client_id : "a1b2c3d4"
    subscription_id : "8a7b6c5d"
    tenant_id : "6f5g4h3i"
    datalake_name : "rg_data_lake"
  secrets:
    github_client_secret_name : "client_secret"

