name: build-and-deploy-dev
on:
  push:
    branches:
      - 'main'
    
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python3.10-bookworm-slim
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: install
        uses: ./.github/actions/install-deps
          